---
title: "Clustering longitudinal data using TAPIO and clusMLD"
author: "ML"
date: "2025-03-11"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, cache = FALSE)
rerun = FALSE
#devtools::install_github("junyzhou10/clusterMLD")
```

```{r}
library(NbClust)
library(fastcluster)
library(FactoMineR)

source("longTAPIO.R")
source("longTAPIO_try.R")
source("TAPIO.R")
source("calc_SIL.R")
source("association.R")
source("clusMLD_TAPIO.R")

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
data(Longdat, package = "clusterMLD")
```




### clusterMLD data

```{r}
p = "data/"
load(paste0(p, "Longdat_clusters.rda"))
# output = LongDataCluster(Longdat$Dat$obs,
#                          Longdat$Dat[,paste("y", seq(5), sep = "_")],
#                          Longdat$Dat$id)

clusterMLD::MeanPlot(output)
```
```{r}
clusterMLD::DendroPlot(output)
```


This time, we are not interpolating observation times!
Instead we try to replace the call to `hclust()` in the TAPIO routine with code extracted from the `clusterMLD` library:

```{r, eval = rerun, echo = TRUE}
res = clusMLD_TAPIO(as.matrix(Longdat$Dat[,paste("y", seq(5), sep = "_")]),
              user_id = Longdat$Dat$id, obsTimes = Longdat$Dat$obs, k=4, levels=4, n_trees=20)
save(res, file = "data/clusMLD_TAPIO.rda")
```

```{r}
load("data/clusMLD_TAPIO.rda")
trueClusIDs = aggregate(Longdat$Dat$label, function(x) return(x[1]), by = list(Longdat$Dat$id))[,2]
foundClusIDs = res$cl
#confusion matrix
table(foundClusIDs, trueClusIDs)
```


--------------------------

Understanding the structure of the `hclust` object better:

```{r, eval = FALSE}
dim(USArrests)#50  4
hc <- hclust(dist(USArrests), "ave")
plot(hc)
plot(hc, hang = -1)

LEVELS = vector("list", 10)
for(yy in 1:length(LEVELS)){
				cl = cutree(hc, yy+1)
				LEVELS[[yy]] = association(cl)
}
```

